config/routes.rb
Rails.application.routes.draw do
  resources :consultas do
  	collection do
  		get :listar
  	end
  end
  

  resources :pacientes
  resources :dentistas
  get 'paginas/index'

  root :to => 'paginas#index'
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
	validates_presence_of :nome, message: "O nome deve ser preenchido"
	
	validates_uniqueness_of :rg, message: "RG já cadastrado"
	validates_uniqueness_of :cpf, message: "CPF já cadastrado"

	validates_size_of :nome, :minimum=>3, :maximun=>50, message: "Muito pequeno ou muito grande, mínimo de 3 e máximo de 50 caracteres"

	mount_uploader :foto, FotoPacienteUploader

end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  def index 
    @pnome = params[:pnome]
    filtro = "1=1"
    if @pnome != nil
        @pacientes = Paciente.where(filtro+" and nome like '"+ @pnome+"%'").order("nome").paginate(page:params[:page], per_page: 10);
    else
      @pacientes = Paciente.order("nome").paginate(page:params[:page], per_page: 10);
    end
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nome, :rg, :cpf, :nascimento, :telefone, :email, :foto, :endereco)
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_for(@paciente) do |f| %>
  <% if @paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% @paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br><hr>
  <div class="field" id="fleft">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field" >
    <%= f.label :nascimento %><br>
    <%= f.text_field :nascimento, class:'datepicker' %>
  </div>
  
  <div class="field" id="fleft">
    <%= f.label :rg %><br>
    <%= f.text_field :rg, class:'rg'%>
  </div>
  <div class="field" >
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf, class:'cpf' %>
  </div>
  
  <div class="field" id="fleft">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone, class:'tel'%>
  </div>
  <div class="field" >
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field" id="fleft">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>

  <div>
      <%= f.label :foto %>
      <%= image_tag @paciente.foto_url, class: 'foto'  if @paciente.foto? %>
      <%= f.file_field :foto, label: 'Foto' , input_html: {accept: ('application/jpg') } %>
    <br/>
  </div>


  <br><hr>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    <%= link_to ' Voltar', pacientes_path ,  class: "btn btn-default " %>
  </div>
<% end %>

app/views/pacientes/_formbusca.html.erb
<%= form_tag(pacientes_path, method: "get") do%>
	<%= label_tag(:pnome, "Nome ou Parcial:") %>
	<%= text_field_tag(:pnome,  @pnome) %>

	<%=submit_tag 'Buscar', :class => 'btn btn-default'%>
<%end%>

app/views/pacientes/edit.html.erb
<h1>Editando Paciente</h1>

<%= render 'form' %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<br>
<hr>
<%= render 'formbusca'%>
<hr>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Foto</th>
      <th>RG</th>
      <th>CPF</th>
      <th>Data de Nasc.</th>
      <th class='linha_telefone'>Telefone</th>
      <th>Email</th>
      <th>Endereço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nome %></td>
        <td><img style="width:50px;" src=<%= paciente.foto %>></td>
        <td><%= paciente.rg %></td>
        <td><%= paciente.cpf %></td>
        <td><%= paciente.nascimento %></td>
        <td class='linha_telefone'><%= paciente.telefone %></td>
        <td><%= paciente.email %></td>
        <td><%= paciente.endereco %></td>
        <td>
          <%= link_to ' ', edit_paciente_path(paciente),  class: "glyphicon glyphicon-pencil" %>
          <%= link_to ' ', paciente, method: :delete, data: { confirm: 'Deseja excluir este cadastro?' } , class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><hr>

<%=will_paginate @pacientes, previous_label: "Anterior", next_label: "Próxima"%>

<%= link_to 'Novo Paciente', new_paciente_path %>

app/views/pacientes/new.html.erb
<h1>Novo Paciente</h1>

<%= render 'form' %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @paciente.nome %>
</p>

<p>
  <strong>RG:</strong>
  <%= @paciente.rg %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @paciente.cpf %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= @paciente.nascimento %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @paciente.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @paciente.email %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @paciente.endereco %>
</p>


<%= link_to 'Editar', edit_paciente_path(@paciente) %> |
<%= link_to 'Voltar', pacientes_path %>