config/routes.rb
Rails.application.routes.draw do
  resources :consultas do
  	collection do
  		get :listar
  	end
  end
  

  resources :pacientes
  resources :dentistas
  get 'paginas/index'

  root :to => 'paginas#index'
end

app/models/dentista.rb
class Dentista < ActiveRecord::Base
	validates_presence_of :nome, message: "O nome deve ser preenchido"
	validates_presence_of :especialidade, message: "A especialidade deve ser preenchida"
	
	validates_uniqueness_of :rg, message: "RG já cadastrado"
	validates_uniqueness_of :cpf, message: "CPF já cadastrado"
	validates_uniqueness_of :cro, message: "CRO já cadastrado"

	validates_size_of :nome, :minimum=>3, :maximun=>50, message: "Muito pequeno ou muito grande, mínimo de 3 e máximo de 50 caracteres"
	validates_numericality_of :salario, message: "O salário deve ser numérico"
end

app/controllers/dentistas_controller.rb
class DentistasController < ApplicationController
  before_action :set_dentista, only: [:show, :edit, :update, :destroy]

  # GET /dentistas
  # GET /dentistas.json
  def index
    @dentistas = Dentista.all
  end

  # GET /dentistas/1
  # GET /dentistas/1.json
  def show
  end

  # GET /dentistas/new
  def new
    @dentista = Dentista.new
  end

  # GET /dentistas/1/edit
  def edit
  end

  def index 
    @pnome = params[:pnome]
    filtro = "1=1"
    if @pnome != nil
        @dentistas = Dentista.where(filtro+" and nome like '"+ @pnome+"%'").order("nome").paginate(page:params[:page], per_page: 10);
    else
      @dentistas = Dentista.order("nome").paginate(page:params[:page], per_page: 10);
    end
  end

  # POST /dentistas
  # POST /dentistas.json
  def create
    @dentista = Dentista.new(dentista_params)

    respond_to do |format|
      if @dentista.save
        format.html { redirect_to @dentista, notice: 'Dentista was successfully created.' }
        format.json { render :show, status: :created, location: @dentista }
      else
        format.html { render :new }
        format.json { render json: @dentista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dentistas/1
  # PATCH/PUT /dentistas/1.json
  def update
    respond_to do |format|
      if @dentista.update(dentista_params)
        format.html { redirect_to @dentista, notice: 'Dentista was successfully updated.' }
        format.json { render :show, status: :ok, location: @dentista }
      else
        format.html { render :edit }
        format.json { render json: @dentista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dentistas/1
  # DELETE /dentistas/1.json
  def destroy
    @dentista.destroy
    respond_to do |format|
      format.html { redirect_to dentistas_url, notice: 'Dentista was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dentista
      @dentista = Dentista.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dentista_params
      params.require(:dentista).permit(:nome, :especialidade, :cro, :salario, :rg, :cpf, :nascimento, :telefone, :email, :endereco)
    end
end

app/helpers/dentistas_helper.rb
module DentistasHelper
end

app/views/dentistas/_form.html.erb
<%= form_for(@dentista) do |f| %>
  <% if @dentista.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dentista.errors.count, "error") %> prohibited this dentista from being saved:</h2>

      <ul>
      <% @dentista.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="field" id="fleft">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :nascimento %><br>
    <%= f.text_field :nascimento, class:'datepicker'%>
  </div>
  <div class="field" id="fleft">
    <%= f.label :cro %><br>
    <%= f.text_field :cro %>
  </div>
  <div class="field">
    <%= f.label :especialidade %><br>
    <%= f.text_field :especialidade %>
  </div>
  <div class="field" id="fleft">
    <%= f.label :salario %><br>
    <%= f.text_field :salario %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone, class:'tel'%>
  </div>
  <div class="field" id="fleft">
    <%= f.label :rg %><br>
    <%= f.text_field :rg, class:'rg'%>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf, class:'cpf' %>
  </div>
  <div class="field" id="fleft">
    <%= f.label :email %><br>
    <%= f.text_field :email%>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco, id:'endereco'%>
  </div>

  <br><hr>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    <%= link_to ' Voltar', dentistas_path ,  class: "btn btn-default " %>
  </div>
<% end %>

app/views/dentistas/_formbusca.html.erb
<%= form_tag(dentistas_path, method: "get") do%>
	<%= label_tag(:pnome, "Nome ou Parcial:") %>
	<%= text_field_tag(:pnome,  @pnome) %>

	<%=submit_tag 'Buscar', :class => 'btn btn-default'%>
<%end%>

app/views/dentistas/edit.html.erb
<h1>Editando Dentista</h1>

<%= render 'form' %>

app/views/dentistas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dentistas</h1>

<br>
<hr>
<%= render 'formbusca'%>
<hr>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Especialidade</th>
      <th>CRO</th>
      <th>Salario</th>
      <th>RG</th>
      <th>CPF</th>
      <th>Data de Nasc.</th>
      <th class='linha_telefone'>Telefone</th>
      <th>Email</th>
      <th>Endereço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dentistas.each do |dentista| %>
      <tr>
        <td><%= dentista.nome %></td>
        <td><%= dentista.especialidade %></td>
        <td><%= dentista.cro %></td>
        <td><%= dentista.salario %></td>
        <td><%= dentista.rg %></td>
        <td><%= dentista.cpf %></td>
        <td><%= dentista.nascimento %></td>
        <td class='linha_telefone'><%= dentista.telefone %></td>
        <td><%= dentista.email %></td>
        <td><%= dentista.endereco %></td>
        <td>
          <%= link_to ' ', edit_dentista_path(dentista),  class: "glyphicon glyphicon-pencil" %>
          <%= link_to ' ', dentista, method: :delete, data: { confirm: 'Deseja excluir este cadastro?' } , class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><hr>

<%= link_to 'Novo Dentista', new_dentista_path %>

app/views/dentistas/new.html.erb
<h1>Novo Dentista</h1>

<%= render 'form' %>

app/views/dentistas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @dentista.nome %>
</p>

<p>
  <strong>Especialidade:</strong>
  <%= @dentista.especialidade %>
</p>

<p>
  <strong>CRO:</strong>
  <%= @dentista.cro %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @dentista.salario %>
</p>

<p>
  <strong>RG:</strong>
  <%= @dentista.rg %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @dentista.cpf %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= @dentista.nascimento %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @dentista.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dentista.email %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @dentista.endereco %>
</p>


<%= link_to 'Editar', edit_dentista_path(@dentista) %> |
<%= link_to 'Voltar', dentistas_path %>