config/routes.rb
Rails.application.routes.draw do
  resources :consultas do
  	collection do
  		get :listar
  	end
  end
  

  resources :pacientes
  resources :dentistas
  get 'paginas/index'

  root :to => 'paginas#index'
end

app/models/consulta.rb
class Consulta < ActiveRecord::Base
	validates_presence_of :data, message: "A data deve ser preenchida"
	validates_presence_of :hora, message: "A hora deve ser preenchida"

	belongs_to :dentista
	belongs_to :paciente
end

app/controllers/consultas_controller.rb
class ConsultasController < ApplicationController
  before_action :set_consulta, only: [:show, :edit, :update, :destroy]

  # GET /consultas
  # GET /consultas.json
  def index
    @consultas = Consulta.all
  end

  # GET /consultas/1
  # GET /consultas/1.json
  def show
  end

  # GET /consultas/new
  def new
    @consulta = Consulta.new
  end

  # GET /consultas/1/edit
  def edit
  end

  def index 
    @pdata = params[:pdata]
    filtro = "1=1"

    if !@pdata.nil? && !@pdata.empty?
      @consultas = Consulta.where(filtro+" and data == '"+@pdata+"'").order("data").paginate(page:params[:page], per_page: 10);
    else
      @consultas = Consulta.order("data").paginate(page:params[:page], per_page: 10);
    end
  end

  def listar
    @consultas = Consulta.all

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ConsultasReport.new(@consultas)
        send_data pdf.render, filename: 'ConsultasListagem.pdf', :width => pdf.bounds.width, type: 'application/pdf', disposition: :inline, :page_size => "A4", :page_layout => :portrait
      end
    end
  end

  # POST /consultas
  # POST /consultas.json
  def create
    @consulta = Consulta.new(consulta_params)

    respond_to do |format|
      if @consulta.save
        format.html { redirect_to @consulta, notice: 'Consulta was successfully created.' }
        format.json { render :show, status: :created, location: @consulta }
      else
        format.html { render :new }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultas/1
  # PATCH/PUT /consultas/1.json
  def update
    respond_to do |format|
      if @consulta.update(consulta_params)
        format.html { redirect_to @consulta, notice: 'Consulta was successfully updated.' }
        format.json { render :show, status: :ok, location: @consulta }
      else
        format.html { render :edit }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultas/1
  # DELETE /consultas/1.json
  def destroy
    @consulta.destroy
    respond_to do |format|
      format.html { redirect_to consultas_url, notice: 'Consulta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consulta
      @consulta = Consulta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consulta_params
      params.require(:consulta).permit(:data, :hora, :dentista_id, :paciente_id)
    end
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/views/consultas/_form.html.erb
<%= form_for(@consulta) do |f| %>
  <% if @consulta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consulta.errors.count, "error") %> prohibited this consulta from being saved:</h2>

      <ul>
      <% @consulta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data , class: 'datepicker'%>
  </div>
  <div class="field">
    <%= f.label :hora %><br>
    <%= f.text_field :hora, id: 'hora'%>
  </div>
  <div class="field>">
    <%= f.label :dentista_id %><br>
    <%= f.select :dentista_id, options_for_select(Dentista.all.map{|m|[m.nome, m.id]}, f.object.dentista_id) %>
  </div>
  <div class="field>">
    <%= f.label :paciente_id %><br>
    <%= f.select :paciente_id, options_for_select(Paciente.all.map{|m|[m.nome, m.id]}, f.object.paciente_id) %>
  </div>
  <br><hr>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
    <%= link_to ' Voltar', consultas_path ,  class: "btn btn-default " %>
  </div>
<% end %>

app/views/consultas/_formbusca.html.erb
<%= form_tag(consultas_path, method: "get") do%>
	<%= label_tag(:pdata, "Data:") %>	
	<%= text_field_tag(:pdata,  @pdata, id: 'field_busca', class: 'datepicker2') %>

	<%=submit_tag 'Buscar', :class => 'btn btn-default'%>
<%end%>

app/views/consultas/edit.html.erb
<h1>Editando Consulta</h1>

<%= render 'form' %>

app/views/consultas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consultas</h1>

<br>
<hr>
<%= render 'formbusca'%>
<hr>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Hora</th>
      <th>Dentista</th>
      <th>Paciente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultas.each do |consulta| %>
      <tr>

        <td><%= consulta.data %></td>
        <td><%= consulta.hora %></td>
        <td><%=consulta.dentista.nome if consulta.dentista %></td>
        <td><%=consulta.paciente.nome if consulta.paciente %></td>
        <td>
          <%= link_to ' ', edit_consulta_path(consulta),  class: "glyphicon glyphicon-pencil" %>
          <%= link_to ' ', consulta, method: :delete, data: { confirm: 'Deseja excluir este cadastro?' } , class: "glyphicon glyphicon-trash" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><hr>

<%=will_paginate @consultas, previous_label: "Anterior", next_label: "Próxima"%>

<%= link_to 'Nova Consulta', new_consulta_path %>

app/views/consultas/new.html.erb
<h1>Nova Consulta</h1>

<%= render 'form' %>

app/views/consultas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @consulta.data %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @consulta.hora %>
</p>

<p>
  <strong>Dentista:</strong>
  <%= @consulta.dentista %>
</p>

<p>
  <strong>Paciente:</strong>
  <%= @consulta.paciente %>
</p>

<%= link_to 'Editar', edit_consulta_path(@consulta) %> |
<%= link_to 'Voltar', consultas_path %>