config/routes.rb
Rails.application.routes.draw do
  resources :consultas do
  	collection do
  		get :listar
  	end
  end
  

  resources :pacientes
  resources :dentistas
  get 'paginas/index'

  root :to => 'paginas#index'
end

app/views/layouts/_latbar.html.erb
  
<div id="wrapper">
	<div id="sidebar-wrapper">
   <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="#" >
       <h4>Menu</h4>
     </a>
   </li>
   
   <li style="font-size: 20px;">
     <%= link_to ' Clínica', paginas_index_path,class: "glyphicon glyphicon-home" %>  
   </li>
   <li style="font-size: 20px;">
     <%= link_to ' Dentistas', dentistas_path ,class: "glyphicon glyphicon-user"%>
   </li>
   <li style="font-size: 20px;">
     <%= link_to ' Pacientes', pacientes_path ,class: "glyphicon glyphicon-user"%>
   </li>
   <li style="font-size: 20px;">
     <%= link_to ' Consultas', consultas_path  ,class: "glyphicon glyphicon-user"%>
   </li>
  <li style="font-size: 20px;">
     <%= link_to ' Relatório', listar_consultas_path(@consulta, :format => 'pdf'), target: '_blank' ,class: "glyphicon glyphicon-print"%>
   </li>
 </ul>
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Consultório Odontológico</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= image_tag 'logo-iff-small.png', class: 'logo'%>

	<%= render "layouts/navbar" %>


	<div class="container">
		<div class="row">
			<div class="col-md-3">	
				<%= render "layouts/latbar" %>
			</div>
			<div class="col-md-9">
				<div class="panel-body">
					<%= yield %>	
					<p class="notice"><%= notice %></p>
					<p class="alert"><%= alert %></p>
				</div>
			</div>
		</div> <!-- row -->
	</div> <!-- container -->

</body>
</html>